# Generated by Django 5.0.7 on 2024-07-31 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_userprofile'),
        ('tenant_app', '0003_remove_hotel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insta.client'),
            preserve_default=False,
        ),
    ]
