# Generated by Django 5.0.7 on 2024-08-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_userprofile_verification_token'),
        ('tenant_app', '0004_hotel_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='insta.client'),
        ),
    ]
